name: Run Nix Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        lisp:
          - ecl
          - sbcl
          - abcl
          - ccl
        os:
          - ubuntu-latest
          - macos-latest

    name: Test on ${{ matrix.os }} with ${{ matrix.lisp }}

    if: !(matrix.os == 'macos-latest' && matrix.lisp == 'ccl')

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run Nix Test
        run: nix run .#test-${{ matrix.lisp }}
